import React from 'react'

export default function Specs() {
  return (
    <div>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt blanditiis optio odio minima deserunt enim ad at corrupti, quo dicta quia aliquid, eius suscipit mollitia repellendus? Totam animi recusandae rem non laudantium, doloribus distinctio aperiam, alias officiis suscipit, minima eaque. Maiores maxime odit, asperiores ipsum aut ipsa iure dolores veniam officia dignissimos amet nesciunt assumenda iusto culpa mollitia provident similique rerum repellendus, deserunt saepe eos adipisci quisquam commodi. Nam inventore, maxime deleniti illo magni reiciendis architecto dignissimos. Est nostrum dicta praesentium, ea cumque dignissimos rem neque perspiciatis quam tempore possimus qui quas, quis animi placeat voluptatum soluta voluptas distinctio voluptatem ullam magni tenetur quos fugiat sunt. Eveniet provident beatae recusandae unde deserunt harum ullam qui? Dignissimos temporibus possimus, qui adipisci fugit illum eveniet sunt illo porro nulla fugiat amet natus assumenda deserunt magni dolorem perspiciatis nisi ea obcaecati sequi rerum. Nam possimus maiores, iure similique, fugiat fuga omnis provident debitis laborum, reiciendis accusantium excepturi rem officiis quia dolorum odio quaerat porro nesciunt corporis eligendi aperiam commodi consequuntur dolorem cupiditate? Amet ad culpa, repellendus tempora at id et, nobis eius tempore unde facilis temporibus accusantium odit delectus perferendis vitae, impedit voluptatum. Rem vitae reiciendis, veritatis nulla sed, accusantium debitis aliquam vero necessitatibus dolore voluptates eligendi quaerat voluptatum! Eum sed dolor nesciunt eaque sint accusamus voluptate quae quisquam quasi! Quae magni culpa officia accusantium, doloribus reprehenderit minus? Nulla autem qui veniam voluptate optio explicabo quibusdam quod, enim quos! Dolor impedit amet ducimus reiciendis iste possimus porro, necessitatibus quos deleniti pariatur laudantium modi saepe architecto labore corporis nesciunt! Vitae rerum veritatis laudantium odio. Consectetur molestias ex officia illo? Eaque odio quam aperiam libero quae necessitatibus quod error non nam, voluptatem ea neque voluptate doloribus, ducimus quia nobis ab cum dolore dignissimos saepe quaerat animi deserunt ipsum. Atque sunt laudantium inventore illum enim magni?
    </div>
  )
}
